apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: savyo-web-ingress
  namespace: prod
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: www.savvyo.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: savyo-web-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.savvyo.in
      secretName: letsencrypt-prod
