name: Deploy on prod namespace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Kubernetes deployment
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.30.2'
      id: install

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA .
    

    - name: Push Docker image to ECR
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA ${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA
        docker push ${{ secrets.ECR_REPOSITORY }}:latest


    - name: Get EKS cluster credentials
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/prod/deployment.yaml
        kubectl apply -f kubernetes/prod/service.yaml
